[package]
name = "Pickpocket Minigame"
description = "tbd"
homepage = "https://www.nexusmods.com/morrowind/mods/xxx"
repository = "https://github.com/rfuzzo/tes3-mods"
authors = ["rfuzzo"]
version = "1.0"

[tools.mwse]
lua-mod = "rfuzzo.kcdpickpocket"

[dependencies.mwse]
buildnumber = 3074
