[package]
name = "Immersive Vehicles"
description = "A mod that adds real-time travel with a number of vehicles."
homepage = "https://www.nexusmods.com/morrowind/mods/54063"
repository = "https://github.com/rfuzzo/tes3-mods"
authors = ["rfuzzo"]
version = "1.0.0"

[tools.mwse]
lua-mod = "rfuzzo.ImmersiveVehicles"

[dependencies.mwse]
buildnumber = 3676
